### ISSUE TITLE
A way to determine if code is stale

### ISSUE THREAD

**Issue by andrechen77** [NetLogo-Mobile/CodeMirror-NetLogo#109]
The way the old editor determined if the code was stale was by continuously [comparing](https://github.com/NetLogo/Galapagos/blob/52efb5c02bbbd3ed5a6625857b45547dc1cd5041/app/assets/javascripts/beak/widgets/ractives/code-editor.coffee#L28C5-L28C64) the editor contents (as a string) with the most recently compiled code. This approach [converts](https://github.com/NetLogo/Galapagos/blob/52efb5c02bbbd3ed5a6625857b45547dc1cd5041/app/assets/javascripts/beak/widgets/ractives/subcomponent/code-container.coffee#L38-L40C21) the contents to a string every time the editor's contents change, which seems to defeat the purpose of the editor having its own optimized representation of the contents. To avoid this, I made it so that code was considered stale as soon as some change was made, without actually comparing the contents. The downside is that if the code is edited to be the exact same as the most recently compiled code, we don't realize that the code has become "unstale," whereas the old approach would have realized.

IMO this behavior makes a lot of sense anyway so perhaps we don't even need this feature.

**Comment by CIVITAS-John** [comment]
I think it won't matter for most people. Consider this as very low priority. Thanks

**Comment by andrechen77** [comment]
I think this new behavior makes more sense anyway. This request is unnecessary.
