### ISSUE TITLE
Better special key bindings

### ISSUE THREAD

**Issue by andrechen77** [NetLogo-Mobile/CodeMirror-NetLogo#111]
There should be a better way to specify special key handlers besides `OnKeyUp`, which:
- doesn't wait until key-up to run the handler, and
- blocks the key's default action (such as inserting a character or moving the cursor for the arrow keys).

Blocking the default effect is something [the old CodeMirror](https://github.com/NetLogo/Galapagos/blob/8ff744d90385f349d035081fd44e2902b3def948/app/assets/javascripts/beak/widgets/ractives/console.coffee#L78-L83) had. As of right now, we have no way of knowing when a key is pressed until after it has already been released (since many of the special keys only work with [the OnKeyUp handler](https://github.com/NetLogo-Mobile/CodeMirror-NetLogo/blob/12a1edaaa2ac74d58f78bbea1a26926ca3179dc6/src/editor-config.ts#L24-L25)), at which point it's too late. In particular, pressing the tab key (to switch between which agent set is executing commands) actually inserts a tab character, which we then have to delete later on. This is not only inelegant but also the user can visually see the text wobble as the tab is inserted and quickly removed.

(`OnKeyDown` doesn't work for some keys, such as Enter and the arrow keys, but this is unrelated.)

**Comment by andrechen77** [comment]
The fact that specials keys such as Tab can only be bound via `OnKeyUp` also means that alt-tabbing into the window when the command center is focused causes it to cycle agent-sets, which was not an issue with the old CodeMirror.

**Comment by andrechen77** [comment]
This also means that using tab-complete will cycle agent-sets. D:

**Comment by CIVITAS-John** [comment]
Opened up `KeyBindings` in Options with CodeMirror's original API. Just a very thin layer of wrapping.
