### ISSUE TITLE
Add ParseMode for multiline reporters

### ISSUE THREAD

**Issue by andrechen77** [NetLogo-Mobile/CodeMirror-NetLogo#115]
This new option should be the same as [one-line reporter mode](https://github.com/NetLogo-Mobile/CodeMirror-NetLogo/blob/12a1edaaa2ac74d58f78bbea1a26926ca3179dc6/src/editor-config.ts#L53C3-L53C19), but it allows code to span multiple lines like the "Embedded" option.

**Comment by CIVITAS-John** [comment]
The request results in a breaking change: `OnelineReporter` is now renamed as `Reporter`. You can still set the `OneLine` property to distinguish between multi-line reporter input and single-line reporter input.
