### ISSUE TITLE
Debug statements were left in the code

### ISSUE THREAD

**Issue by andrechen77** [NetLogo-Mobile/CodeMirror-NetLogo#120]
The following is a screenshot of what the console looks like after loading two `GalapagosEditor`s and typing into one of them.

![image](https://github.com/NetLogo-Mobile/CodeMirror-NetLogo/assets/101299705/57cd2531-e08e-4dfa-87f8-fa227e602666)

Unfortunately the console only shows that the message came from some weird location in the bundled file, since that's how codemirror-netlogo is consumed by Galapagos. This is using [version 0.3.0](https://www.npmjs.com/package/@netlogo/codemirror-netlogo/v/0.3.0), which was created from e9b25ee0e61c9cb85d140396bd5eb1192161e3a3.

**Comment by andrechen77** [comment]
There are also debug statements printed when the user hovers over a token (which may or may not generate a tooltip).

![image](https://github.com/NetLogo-Mobile/CodeMirror-NetLogo/assets/101299705/a0e4cc0c-7ca0-4efc-b33e-6768dade45e8)

**Comment by CIVITAS-John** [comment]
`window.GalapagosSilent = true` shall solve it. Does NLW have a debug mode too? If so, the two should be linked.

**Comment by andrechen77** [comment]
Shouldn't the production build have `window.GalapagosSilent` already set?
