### ISSUE TITLE
Use different icons for different autocompletion options

### ISSUE THREAD

**Issue by CIVITAS-John** [NetLogo-Mobile/CodeMirror-NetLogo#9]

**Comment by wubbalubbadu** [comment]
1. Give completions their own render methods. I think this is the newer and preferred way. The related documentation and sample code is in the link below.
https://discuss.codemirror.net/t/how-to-add-icon-to-list-which-appare-when-i-do-autocomplete/944/2
2. Add a className property to a completion. Sample code in link below.
https://discuss.codemirror.net/t/customizing-autocompletion-hint-items-by-adding-image-before-it/1248
